import { AIProvider, AIAnalysisResult } from './aiProvider';

export class AnthropicProvider implements AIProvider {
  private apiKey: string;
  private model: string;

  constructor() {
    this.apiKey = process.env.ANTHROPIC_API_KEY || '';
    // Use Claude 3.5 Sonnet by default
    this.model = process.env.ANTHROPIC_MODEL || 'claude-3-5-sonnet-20240620';
  }

  async analyzeConversation(transcript: string, promptTemplate: string): Promise<AIAnalysisResult> {
    if (!this.apiKey) {
      throw new Error('Anthropic API key is not configured (ANTHROPIC_API_KEY environment variable is missing).');
    }

    const prompt = promptTemplate.replace('{{TRANSCRIPT}}', transcript);

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'x-api-key': this.apiKey,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1200,
          messages: [
            {
              role: 'user',
              content: prompt,
            },
          ],
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Claude API request failed: ${response.status} ${response.statusText} - ${errorText}`);
      }

      interface AnthropicMessageResponse {
        content?: Array<{ text?: string }>;
      }

      const responseData = (await response.json()) as AnthropicMessageResponse;
      const rawText = responseData.content?.[0]?.text || '';
      
      // Find the first '{' and the last '}' to extract JSON body (handles conversational prefix/suffix)
      const startIndex = rawText.indexOf('{');
      const endIndex = rawText.lastIndexOf('}');
      if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
        throw new Error(`Failed to locate JSON block in Claude response: "${rawText}"`);
      }
      const cleanJson = rawText.substring(startIndex, endIndex + 1).trim();
      const parsed = JSON.parse(cleanJson);

      // Parse budget field robustly
      let budgetVal: number | null = null;
      if (typeof parsed.budget === 'number') {
        budgetVal = parsed.budget;
      } else if (typeof parsed.budget === 'string') {
        const cleaned = parsed.budget.replace(/[^0-9.]/g, '');
        const parsedNum = parseFloat(cleaned);
        if (!isNaN(parsedNum)) {
          budgetVal = Math.round(parsedNum);
        }
      }

      return {
        budget: budgetVal,
        preferredUnit: parsed.preferredUnit || null,
        timeline: parsed.timeline || null,
        financingStatus: parsed.financingStatus || null,
        intent: parsed.intent || null,
        leadScore: parsed.leadScore === 'HOT' || parsed.leadScore === 'WARM' || parsed.leadScore === 'COLD' ? parsed.leadScore : 'COLD',
        reasoning: parsed.reasoning || 'No reasoning details provided by Claude.',
        rawResponse: rawText,
      };
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : 'Unknown error';
      throw new Error(`Claude AI analysis execution failed: ${errMsg}`);
    }
  }

  async summarizeConversation(transcript: string, promptTemplate: string): Promise<string> {
    if (!this.apiKey) {
      throw new Error('Anthropic API key is not configured (ANTHROPIC_API_KEY environment variable is missing).');
    }

    const prompt = promptTemplate.replace('{{TRANSCRIPT}}', transcript);

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'x-api-key': this.apiKey,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 600,
          messages: [
            {
              role: 'user',
              content: prompt,
            },
          ],
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Claude API request failed: ${response.status} ${response.statusText} - ${errorText}`);
      }

      interface AnthropicMessageResponse {
        content?: Array<{ text?: string }>;
      }

      const responseData = (await response.json()) as AnthropicMessageResponse;
      return responseData.content?.[0]?.text || 'No summary text generated by Claude.';
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : 'Unknown error';
      throw new Error(`Claude AI summarization execution failed: ${errMsg}`);
    }
  }

  async generateDraft(transcript: string, promptTemplate: string): Promise<string> {
    if (!this.apiKey) {
      throw new Error('Anthropic API key is not configured (ANTHROPIC_API_KEY environment variable is missing).');
    }

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: {
          'x-api-key': this.apiKey,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 600,
          messages: [
            {
              role: 'user',
              content: promptTemplate,
            },
          ],
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Claude API request failed: ${response.status} ${response.statusText} - ${errorText}`);
      }

      interface AnthropicMessageResponse {
        content?: Array<{ text?: string }>;
      }

      const responseData = (await response.json()) as AnthropicMessageResponse;
      return responseData.content?.[0]?.text || 'No response draft generated by Claude.';
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : 'Unknown error';
      throw new Error(`Claude AI draft generation execution failed: ${errMsg}`);
    }
  }
}
